### ISSUE TITLE
Couple of problems

### ISSUE THREAD

**Issue by cjtganzon** [TubYoub/VelocityPteroPower#4]
i was looking for something for velocity with the functionality of mcsleepingserverstarter and the serversleeper plugin and came across this plugin! and the fact that i can start and stop servers from in game is a big plus! unfortunately i ran into problems right away

here is my log https://mclo.gs/w6dvasJ

1. commands from console dont work, only from the player. maybe you didnt implement it yet?
2. i keep getting this error trying to connect to an offline server to start it
```
[Velocity Async Event Executor - #2/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ServerPreConnectEvent to velocity-ptero-power 0.9
java.lang.NullPointerException: Cannot invoke "de.tubyoub.velocitypteropower.api.PterodactylAPIClient.isServerOnline(String)" because "this.pterodactylAPIClient" is null
```
3. i also get this error trying to start and stop with in game command
```
[Velocity Async Event Executor - #9/ERROR] [velocity-ptero-power]: Error powering server.
java.net.ConnectException: null
```
4. after no players on a server, it tries to shutdown the server with no success with an error similar to problem 2. from a log that is not attached:
```
[VelocityPteroPower - Task Executor #2/ERROR] [com.velocitypowered.proxy.scheduler.VelocityScheduler.VelocityTask]: Exception in task de.tubyoub.velocitypteropower.VelocityPteroPower$$Lambda/0x00007fc18d19a908@7deb78cf by plugin VelocityPteroPower
java.lang.NullPointerException: Cannot invoke "de.tubyoub.velocitypteropower.api.PterodactylAPIClient.isServerEmpty(String)" because "this.pterodactylAPIClient" is null
```

im not sure what im doing wrong. i have the latest ptero panel 1.11.7 with an account api created with any allowed ip's

**Comment by TubYoub** [comment]
Hi thanks for reporting,
So first of all the Plugin is not yet feature complete, thats why it is still beta.
The plugin was only for my specific needs but i will try to ship a stable version in the next few day (or week).
1. Yes the commands are not yet usable in the console. 
2/3/4. I changed a few things in the last release because i implemented the Pelican Panel and did a big oupsi because i did not test the Plugin....
Gotta get right to it. New version will be up in a few Minutes on [Modrinth](https://modrinth.com/plugin/velocitypteropower/versions)

Join our [Discord](https://discord.pluginz.dev)to get Support and never miss a new Version again
